"""add theme preset to user

Revision ID: 24269189aa70
Revises: ad4b6d38a0f0
Create Date: 2026-02-09 22:51:23.251618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24269189aa70'
down_revision: Union[str, Sequence[str], None] = 'ad4b6d38a0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme_preset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme_preset')
    # ### end Alembic commands ###
