"""add custom css to user

Revision ID: ad4b6d38a0f0
Revises: 8c31f8f1b4ee
Create Date: 2026-02-09 22:40:04.037531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4b6d38a0f0'
down_revision: Union[str, Sequence[str], None] = '8c31f8f1b4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_css', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_css')
    # ### end Alembic commands ###
